services:
  db:
    image: postgres:16
    container_name: rescue_postgres
    restart: always
    environment:
      POSTGRES_USER: rescue_user
      POSTGRES_PASSWORD: rescue_pass
      POSTGRES_DB: rescue_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: rescue_api
    build:
      context: .
      dockerfile: ./src/RescueSystem.Api/Dockerfile
    restart: always
    ports:
      - "7043:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db

volumes:
  pgdata:
    driver: local